### ISSUE TITLE
Corrupt HTTP response header for some requests (depending on the attachment)

### ISSUE THREAD

**Issue by srogatch** [oatpp/oatpp#258]
It seems that `oatpp` corrupts HTTP response headers depending on the attachment.
Here is the approximate code that triggers the issue:
```cpp
shared_ptr<oatpp::web::server::HttpRequestHandler::OutgoingResponse> DownloadRequestHandler::handle(
  const std::shared_ptr<IncomingRequest>& request)
{
  const oatpp::String sBlockToken = request->getQueryParameter("BlockToken");
  // ...
  oatpp::String bytes(oatpp::base::StrBuffer::loadFromFile("Blocks\\01d6403becf973ecab3de90093b82e07.zip"));
  shared_ptr<OutgoingResponse> response = ResponseFactory::createResponse(Status::CODE_200, bytes);
  response->putHeader("Content-Type", "application/zip");
  response->putHeader("Content-Disposition", "attachment; filename=\"01d6403becf973ecab3de90093b82e07.zip\"");
  return response;
}
```
The Python library `requests` reports the issue as follows after trying to download the file:
```
2020-06-12 09:53:33,890 WARNING: Failed to parse headers (url=http://127.0.0.1:88/download?BlockToken=01d6403becf973ecab3de90093b82e07): [MissingHeaderBodySeparatorDefect()], unparsed data: 'é\x89n\x02\x00\x00nt; filename="01d6403becf973ecab3de90093b82e07.zip"\r\nContent-Length: 3521178\r\n\r\n'
Traceback (most recent call last):
  File "anonymized\venv\FetchingUI\lib\site-packages\urllib3\connectionpool.py", line 446, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "anonymized\venv\FetchingUI\lib\site-packages\urllib3\util\response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'é\x89n\x02\x00\x00nt; filename="01d6403becf973ecab3de90093b82e07.zip"\r\nContent-Length: 3521178\r\n\r\n'
```
I tested also in Chrome and in Postman: they all complain about a corrupt HTTP header in the response. So it's not a bug of Python's `requests` library.

The bug happens only for some attachments. [Here you can find an example attachment](https://github.com/srogatch/upload/blob/master/Bugs/oatpp/CorruptHeader/01d6403becf973ecab3de90093b82e07.zip?raw=true).

The oatpp version used is 1.0.0 release. Compiled on Windows 10 64-bit with Visual Studio 2019 v.16.6.1 .

**Comment by lganzzzo** [comment]
Hello @srogatch ,

Thanks for the issue!

As I understand, in your real code here you do string contamination:
```cpp
response->putHeader("Content-Disposition", "attachment; filename=\"01d6403becf973ecab3de90093b82e07.zip\"");
```

Can you please post the code how you do string concat and how you pass it to the header.

**Comment by srogatch** [comment]
Yes, I concatenate strings but the code is too complex to post because there is a whole framework with memory pooling and custom allocators for STL objects. I do string concatenation roughly as follows:
```
const oatpp::String sBlockToken = request->getQueryParameter("BlockToken");
const string justFileName = string(sBlockToken->c_str()) + ".zip";
// ...
const string contentDisposition = string("attachment; filename=\"") + string(justFileName) + string("\"");
response->putHeader("Content-Disposition", contentDisposition.c_str());
```

**Comment by lganzzzo** [comment]
oatpp stores headers as `oatpp::data::share::StringKeyLabel`.
StringKeyLabel - can be treated as a pointer to `oatpp::String` or to existing `const char*`.

You have to be careful not to introduce a memory leak here.

**Example (Memory Leak):**

```cpp
  ENDPOINT("GET", "download", download) {
    auto response = ResponseFactory::createResponse(Status::CODE_200, "<data>");
    oatpp::String a = "header-value";
    response->putHeader("Content-Disposition", a->c_str()); // <-- 'a' is NOT captured here and gonna be destroyed in the end of a block
    return response;
  }
...
  ENDPOINT("GET", "download", download) {
    auto response = ResponseFactory::createResponse(Status::CODE_200, "<data>");
    std::string a = "header-value";
    response->putHeader("Content-Disposition", a.c_str()); // <-- 'a' is NOT captured here and gonna be destroyed in the end of a block
    return response;
  }
```

**Example (Correct)**

```cpp
  ENDPOINT("GET", "download", download) {
    auto response = ResponseFactory::createResponse(Status::CODE_200, "<data>");
    oatpp::String a = "header-value";
    response->putHeader("Content-Disposition", a); // <-- StringKeyLabel captures oatpp::String
    return response;
  }
...
  ENDPOINT("GET", "download", download) {
    auto response = ResponseFactory::createResponse(Status::CODE_200, "<data>");
    std::string a = "header-value";
    response->putHeader("Content-Disposition", oatpp::String(a.data(), a.size(), true)); // <-- captured as oatpp::String
    return response;
  }
```

**Comment by lganzzzo** [comment]
You may use `oatpp::data::stream::BufferOutputStream` for convenient concat directly to `oatpp::String`.

```cpp
  ENDPOINT("GET", "download", download) {
    oatpp::data::stream::BufferOutputStream ss;
    ss << "attachment; filename=\"" << sBlockToken << "\"";
    auto response = ResponseFactory::createResponse(Status::CODE_200, "<data>");
    response->putHeader("Content-Disposition", ss.toString());
    return response;
  }
```

**Comment by lganzzzo** [comment]
So in your code here, is a memory leak, and the header value gets corrupted:

```cpp
const oatpp::String sBlockToken = request->getQueryParameter("BlockToken");
const string justFileName = string(sBlockToken->c_str()) + ".zip";
// ...
const string contentDisposition = string("attachment; filename=\"") + string(justFileName) + string("\"");
response->putHeader("Content-Disposition", contentDisposition.c_str()); //<-- memory leak. 
```

**Comment by srogatch** [comment]
Do you mean that `response->putHeader()` doesn't make a copy of the `const char*` string passed to it?

**Comment by lganzzzo** [comment]
You are correct

**Comment by srogatch** [comment]
Thank you very much for such a prompt response. I have fixed my code with `oatpp::data::stream::BufferOutputStream` as you suggested above. I will try to remember to let you know after my program with your framework is stress-tested again. For now, you can close the issue.

**Comment by lganzzzo** [comment]
> I will try to remember to let you know after my program with your framework is stress-tested again.

Thanks, that would be great!
