### ISSUE TITLE
Crash when calling oatpp::data::mapping::ObjectMapper::writeToString

### ISSUE THREAD

**Issue by harlanc** [oatpp/oatpp#623]
Oatpp  Version : 1.2.5

    #0  0x0000000000000000 in ?? ()
    #1  0x000000000107ab58 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x7f25b00058c0) at /opt/rh/devtoolset-8/root/usr/include/    c++/8/bits/shared_ptr_base.h:155
    #2  0x000000000106ebf7 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7f266a6da638, __in_chrg=<optimized out>) at /opt/rh/    devtoolset-8/root/usr/include/c++/8/bits/shared_ptr_base.h:728
    #3  0x000000000103d124 in std::__shared_ptr<void, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7f266a6da630, __in_chrg=<optimized out>) at /opt/rh/    devtoolset-8/root/usr/include/c++/8/bits/shared_ptr_base.h:1167
    #4  0x000000000103d166 in std::shared_ptr<void>::~shared_ptr (this=0x7f266a6da630, __in_chrg=<optimized out>) at /opt/rh/devtoolset-8/root/usr/include/    c++/8/bits/shared_ptr.h:103
    #5  0x0000000001055bc8 in oatpp::data::mapping::type::ObjectWrapper<void, oatpp::data::mapping::type::__class::Void>::~ObjectWrapper (    this=0x7f266a6da630, __in_chrg=<optimized out>) at /usr/local/include/oatpp-1.2.5/oatpp/oatpp/core/data/mapping/type/Type.hpp:99
    #6  0x0000000002802f48 in oatpp::parser::json::mapping::Serializer::serializeObject(oatpp::parser::json::mapping::Serializer*,     oatpp::data::stream::ConsistentOutputStream*, oatpp::data::mapping::type::ObjectWrapper<void, oatpp::data::mapping::type::__class::Void> const&) ()
    #7  0x000000000280301d in oatpp::parser::json::mapping::Serializer::serialize(oatpp::data::stream::ConsistentOutputStream*,     oatpp::data::mapping::type::ObjectWrapper<void, oatpp::data::mapping::type::__class::Void> const&) ()
    #8  0x0000000002803b96 in void oatpp::parser::json::mapping::Serializer::serializeList<oatpp::data::mapping::type::ListObjectWrapper<    oatpp::data::mapping::type::ObjectWrapper<void, oatpp::data::mapping::type::__class::Void>, oatpp::data::mapping::type::__class::AbstractList>     >(oatpp::parser::json::mapping::Serializer*, oatpp::data::stream::ConsistentOutputStream*, oatpp::data::mapping::type::ObjectWrapper<void,     oatpp::data::mapping::type::__class::Void> const&) ()
    #9  0x000000000280301d in oatpp::parser::json::mapping::Serializer::serialize(oatpp::data::stream::ConsistentOutputStream*,     oatpp::data::mapping::type::ObjectWrapper<void, oatpp::data::mapping::type::__class::Void> const&) ()
    #10 0x0000000002802f3c in oatpp::parser::json::mapping::Serializer::serializeObject(oatpp::parser::json::mapping::Serializer*,     oatpp::data::stream::ConsistentOutputStream*, oatpp::data::mapping::type::ObjectWrapper<void, oatpp::data::mapping::type::__class::Void> const&) ()
    #11 0x000000000280301d in oatpp::parser::json::mapping::Serializer::serialize(oatpp::data::stream::ConsistentOutputStream*,     oatpp::data::mapping::type::ObjectWrapper<void, oatpp::data::mapping::type::__class::Void> const&) ()
    #12 0x00000000028032af in oatpp::parser::json::mapping::Serializer::serializeToStream(oatpp::data::stream::ConsistentOutputStream*,     oatpp::data::mapping::type::ObjectWrapper<void, oatpp::data::mapping::type::__class::Void> const&) ()
    #13 0x0000000002800d00 in oatpp::parser::json::mapping::ObjectMapper::write(oatpp::data::stream::ConsistentOutputStream*,     oatpp::data::mapping::type::ObjectWrapper<void, oatpp::data::mapping::type::__class::Void> const&) const ()
    #14 0x00000000027da01c in oatpp::data::mapping::ObjectMapper::writeToString(oatpp::data::mapping::type::ObjectWrapper<void,     oatpp::data::mapping::type::__class::Void> const&) const ()
    .....
    .....

Have you encountered the similar problems and what‘s the possible reason? Thanks.

**Comment by lganzzzo** [comment]
Hello @harlanc ,

Please make sure to use the latest oatpp - 1.3.0.
Also, please post DTO that you are trying to serialize.

Thanks

**Comment by harlanc** [comment]
Thanks, the problem is sporadic, does version 1.3.0 fix this? and what does "post DTO" mean....
