### ISSUE TITLE
Call async function from other library within async enpoint

### ISSUE THREAD

**Issue by rafaelBauer** [oatpp/oatpp#749]
Hello,

I am trying to have an async call to some other library within an Async endpoint from oatpp, but I am not sure how to do it. I didnt want to block the "act" call. Any ideas how to do this? The setup is:

```
ENDPOINT_ASYNC("GET", "test/isconnected", getTestIsConnected) {

    ENDPOINT_ASYNC_INIT(getTestIsConnected)

      Action act() override {
        // This is the callback of the other library
        std::function<void(bool)> callback = [this](bool connected) {
          Status returnStatus;
          OATPP_LOGD("API", "Test check connection");
          if(!connected){
            returnStatus = Status::CODE_500;
          } else {
            returnStatus = Status::CODE_200;
          }
          controller->createResponse(returnStatus);
        };
        
        // This call returns a void or can also be an std::promise, and the callback gets called as soon as the request finishes.
        otherLibrary->getConnectivityOkay(callback);

        // I don't know what to return here, since I have no real Action unless I block above with a promise and
        // return directly the response with a _return(controller->createDtoResponse(promise.get().get_value()));
        return ??????????; 
      }
  };
```

**Comment by lganzzzo** [comment]
Hello @rafaelBauer ,

The first thing that comes to my mind is to use `oatpp::async::ConditionVariable` :

```cpp
  ENDPOINT_ASYNC("GET", "/hello", MyEndpoint) {
    
    ENDPOINT_ASYNC_INIT(MyEndpoint)

    oatpp::async::Lock m_lock;
    oatpp::async::LockGuard m_lockGuard{&m_lock};
    oatpp::async::ConditionVariable m_cv;

    oatpp::Boolean m_isConnection;

    void callback(bool connected) { // callback will be called concurrently from other lib
      std::lock_guard<oatpp::async::Lock> lockGuard(m_lock); // std lock-guard with oatpp::async::lock
      m_isConnection = connected;
      m_cv.notifyFirst();
    };

    Action act() override {

      otherLibrary->getConnectivityOkay(callback); // NON-BLOCKING async call to other lib

      return m_cv.wait(m_lockGuard, [this]{
        return m_isConnection != nullptr;
      }).next(yieldTo(&MyEndpoint::onResponse));

    }

    Action onResponse() {
      if(m_isConnection) {
        return _return(controller->createResponse(Status::CODE_200, "OK"));
      }
      return _return(controller->createResponse(Status::CODE_500, "NOT OK"));
    }
    
  };
```

**Comment by l2x-huang** [comment]
@lganzzzo     

I add Async endpoint as below, it works.  But when I bench with wrk, it throw an exception.
```cpp
    ENDPOINT_ASYNC("GET", "/hello", Root) {
        ENDPOINT_ASYNC_INIT(Root);

        oatpp::async::Lock lock_;
        oatpp::async::LockGuard lock_guard_{&lock_};
        oatpp::async::ConditionVariable cv_;

        std::shared_ptr<OutgoingResponse> resp_;

        Action act() override {
            async_call("/a/b", "{}", [this](std::string_view s) {
                std::lock_guard<oatpp::async::Lock> _lck(lock_);
                resp_ = controller->createResponse(Status::CODE_200, s.data());
                // OATPP_LOGI("hello", "call end");
                cv_.notifyFirst();
            });

            return cv_.wait(lock_guard_, [this] { return resp_ != nullptr; })
                .next(yieldTo(&Root::onResponse));
        }

        Action onResponse() {
            lock_guard_.unlock();
            // OATPP_LOGI("hello", "responsed");
            return _return(resp_);
        }
    };
```

Excetpion
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  [oatpp::async::Lock::unlock()]: Error. Invalid state.
```

Gdb stack
```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007ffff7aa9d9f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007ffff7a5af32 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff7a45472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007ffff7c9d919 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7ca8e1a in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7ca7e89 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff7ca85a6 in __gxx_personality_v0 () from /lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff7faa934 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#9  0x00007ffff7faaff1 in _Unwind_RaiseException () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#10 0x00007ffff7ca90cb in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x0000555555586ef7 in oatpp::async::Lock::unlock (this=0x7fffdc114478) at /home/cc/ws/cc/zzz/gated/build/_deps/oatpp-src/src/oatpp/core/async/Lock.cpp:66
#12 0x000055555556abc3 in std::lock_guard<oatpp::async::Lock>::~lock_guard (this=0x7ffff7a1db28, __in_chrg=<optimized out>) at /usr/include/c++/12/bits/std_mutex.h:235
#13 0x0000555555568dc1 in MyController::Root::act()::{lambda(std::basic_string_view<char, std::char_traits<char> >)#1}::operator()(std::basic_string_view<char, std::char_traits<char> >) const (
    __closure=0x7fffe001d160, s="/a/b{}") at /home/cc/ws/cc/zzz/gated/src/controller/my_controller.h:38
#14 0x000055555556ea3f in std::__invoke_impl<void, MyController::Root::act()::{lambda(std::basic_string_view<char, std::char_traits<char> >)#1}&, std::basic_string_view<char, std::char_traits<char> > >(std::__invoke_other, MyController::Root::act()::{lambda(std::basic_string_view<char, std::char_traits<char> >)#1}&, std::basic_string_view<char, std::char_traits<char> >&&) (__f=...)
    at /usr/include/c++/12/bits/invoke.h:61
#15 0x000055555556d622 in std::__invoke_r<void, MyController::Root::act()::{lambda(std::basic_string_view<char, std::char_traits<char> >)#1}&, std::basic_string_view<char, std::char_traits<char> > >(MyController::Root::act()::{lambda(std::basic_string_view<char, std::char_traits<char> >)#1}&, std::basic_string_view<char, std::char_traits<char> >&&) (__fn=...) at /usr/include/c++/12/bits/invoke.h:111
#16 0x000055555556c6f6 in std::_Function_handler<void (std::basic_string_view<char, std::char_traits<char> >), MyController::Root::act()::{lambda(std::basic_string_view<char, std::char_traits<char> >)#1}>::_M_invoke(std::_Any_data const&, std::basic_string_view<char, std::char_traits<char> >&&) (__functor=..., __args#0=...) at /usr/include/c++/12/bits/std_function.h:290
#17 0x000055555556a45d in std::function<void (std::basic_string_view<char, std::char_traits<char> >)>::operator()(std::basic_string_view<char, std::char_traits<char> >) const (this=0x7fffe001d160,
    __args#0="/a/b{}") at /usr/include/c++/12/bits/std_function.h:591
#18 0x0000555555565ab0 in operator() (__closure=0x7fffe001d120) at /home/cc/ws/cc/zzz/gated/src/service/rtpsd.h:24
#19 0x0000555555566a18 in std::__invoke_impl<void, async_call(std::string_view, std::string_view, const std::function<void(std::basic_string_view<char>)>&)::<lambda()>&>(std::__invoke_other, struct {...} &) (
```
